### ISSUE TITLE
Trying CompGCN on pharmkg dataset

### ISSUE THREAD

**Issue by Pete2000** [zjukg/NeuralKG#15]
While experimenting with CompGCN a tried to change the embedding size from 100 to 150 and that's the error it returns:
Traceback (most recent call last):
  File "main.py", line 111, in <module>
    main()
  File "main.py", line 101, in main
    trainer.fit(lit_model, datamodule=kgdata)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1311, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1375, in _run_sanity_check
    self._evaluation_loop.run()
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 239, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 219, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/neuralkg/lit_model/CompGCNLitModel.py", line 40, in validation_step
    ranks = link_predict(batch, self.model, prediction='all')
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/neuralkg/eval_task/link_prediction.py", line 18, in link_predict
    tail_ranks = tail_predict(batch, model)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/neuralkg/eval_task/link_prediction.py", line 59, in tail_predict
    pred_score = model.get_score(batch, "tail_predict")
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/neuralkg/model/GNNModel/CompGCN.py", line 127, in get_score
    score = self.ConvE(head_emb, rela_emb, x)
  File "/media/users/caforio/anaconda3/envs/neuralkg/lib/python3.8/site-packages/neuralkg/model/GNNModel/CompGCN.py", line 165, in ConvE
    x = torch.mm(x, all_ent.transpose(1, 0))  # [batch_size, ent_num]
RuntimeError: mat1 and mat2 shapes cannot be multiplied (384x200 and 300x7241)

Here's the configuration:
DATA_DIR=dataset

MODEL_NAME=CompGCN
DATASET_NAME=pharmkg
DATA_PATH=$DATA_DIR/$DATASET_NAME
LITMODEL_NAME=CompGCNLitModel
TRAIN_SAMPLER_CLASS=CompGCNSampler
TEST_SAMPLER_CLASS=CompGCNTestSampler
MAX_EPOCHS=2000
EMB_DIM=150
LOSS_NAME=Cross_Entropy_Loss
TRAIN_BS=2048
EVAL_BS=256
NUM_NEG=1
LR=0.0001
CHECK_PER_EPOCH=50
DECODER_MODEL=ConvE
OPN=mult
NUM_WORKERS=16
GPU=0,1

**Comment by Modberge** [comment]
Thanks for your interest in NeuralKG.  CompGCN is a graph convolutional framework that jointly embeds entities and relations in a knowledge graph.  It uses the ConvE model as the decoder model; for that, we set the fixed convolutional layer and fully connected layer.  Therefore, changing the embedding dimension of the compgcn convolutional layer will lead to the dimension mismatch between the encoder and decoder.
In the subsequent update, we will provide more adjustable hyper-parameters to make the decoder model match the compgcn convolutional layer with different dimensions.

**Comment by Pete2000** [comment]
Many thanks.
