### ISSUE TITLE
运行demo.py报错RuntimeError: Early stopping conditioned on metric `Eval_mrr` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `Train|loss`, `Eval|mrr`, `Eval|hits@10`

### ISSUE THREAD

**Issue by liukuuan-tju** [zjukg/NeuralKG#40]
在windows上把Eval|mrr改成了Eval_mrr，运行demo.py失败并报错：
RuntimeError: Early stopping conditioned on metric `Eval_mrr` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `Train|loss`, `Eval|mrr`, `Eval|hits@10`
`Global seed set to 321
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type     | Params
-----------------------------------
0 | model | TransE   | 662   
1 | loss  | Adv_Loss | 662   
-----------------------------------
660       Trainable params
2         Non-trainable params
662       Total params
0.003     Total estimated model params size (MB)
Epoch 0:  25%|██▌       | 1/4 [00:00<00:00, 83.55it/s, loss=1.12, v_num=8]Global seed set to 321
Epoch 1:  80%|████████  | 4/5 [00:00<00:00, 95.48it/s, loss=0.937, v_num=8]
Validating: 0it [00:00, ?it/s]
Validating:   0%|          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
File "H:\xxxx\20231118-NeuralKG-test\demo.py", line 121, in <module>
    main(arg_path = 'config/TransE_demo_kg.yaml')
  File "H:\xxxx\20231118-NeuralKG-test\demo.py", line 99, in main
    trainer.fit(lit_model, datamodule=kgdata)
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1199, in _run
    self._dispatch()
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1289, in run_stage
    return self._run_train()
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\loops\base.py", line 146, in run
    self.on_advance_end()
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 242, in on_advance_end
    self._run_validation()
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 337, in _run_validation
    self.val_loop.run()
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\loops\base.py", line 151, in run
    output = self.on_run_end()
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 140, in on_run_end
    self._on_evaluation_end()
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 202, in _on_evaluation_end
    self.trainer.call_hook("on_validation_end", *args, **kwargs)
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1495, in call_hook
    callback_fx(*args, **kwargs)
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\trainer\callback_hook.py", line 221, in on_validation_end
    callback.on_validation_end(self, self.lightning_module)
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\callbacks\early_stopping.py", line 194, in on_validation_end
    self._run_early_stopping_check(trainer)
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\callbacks\early_stopping.py", line 200, in _run_early_stopping_check
    if trainer.fast_dev_run or not self._validate_condition_metric(  # disable early_stopping with fast_dev_run
  File "C:\Users\liukuan\.conda\envs\neuralkg2\lib\site-packages\pytorch_lightning\callbacks\early_stopping.py", line 151, in _validate_condition_metric
    raise RuntimeError(error_msg)
RuntimeError: Early stopping conditioned on metric `Eval_mrr` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `Train|loss`, `Eval|mrr`, `Eval|hits@10`
`
想请教一下应该怎么解决？十分感谢！

**Comment by hzwy3c** [comment]
您好，

Earlystopping中monitor的字段有固定要求，建议改回成“Eval|mrr”，如果仍然不行可以尝试检查pytorch_lightning的版本是否为1.5.10。

**Comment by liukuuan-tju** [comment]
谢谢！
