### ISSUE TITLE
在cpu版linux上操作和win7版GPU上操作遇到的问题

### ISSUE THREAD

**Issue by sokolo05** [zjukg/NeuralKG#5]
**cpu版上Linux上执行**
sh scripts/FreeBase/NNE_FB.sh 
报错如下：
---------------------------------------------------------------------------------
Using backend: pytorch
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from neuralkg.utils import setup_parser
  File "/home/laicx/anaconda3/envs/neuralkg/lib/python3.8/site-packages/neuralkg/__init__.py", line 3, in <module>
    from .lit_model import *
  File "/home/laicx/anaconda3/envs/neuralkg/lib/python3.8/site-packages/neuralkg/lit_model/__init__.py", line 1, in <module>
    from .BaseLitModel import BaseLitModel
  File "/home/laicx/anaconda3/envs/neuralkg/lib/python3.8/site-packages/neuralkg/lit_model/BaseLitModel.py", line 6, in <module>
    from neuralkg import loss
  File "/home/laicx/anaconda3/envs/neuralkg/lib/python3.8/site-packages/neuralkg/loss/__init__.py", line 8, in <module>
    from .IterE_Loss import IterE_Loss
ModuleNotFoundError: No module named 'neuralkg.loss.IterE_Loss'
-----------------------------------------------------------------------------------
在win7版GPU设备上使用pycharm执行 
sh NNE_FB.sh
报错如下：
-------------------------------------------------------------------------------------
D:\ProgramData\Anaconda3\envs\neuralkg38\python.exe: can't open file 'main.py': [Errno 2] No such file or directory
-------------------------------------------------------------------------------------

**Comment by sokolo05** [comment]
又看了下 在路径下 没发现 IterE_Loss的文件，其他的9个都有

**Comment by sokolo05** [comment]
后来试了下，在python3.6版本中win7上成功了，Linux上找到了一个IterE_Loss文件放进去之后，运行时候提示：
-------------------------------------------------------------------
raise AssertionError("Torch not compiled with CUDA enabled")
-------------------------------------------------------------------
想必是cpu没法使用吧

**Comment by sokolo05** [comment]
问题已经解决了，是自己对环境太不熟悉了

**Comment by Modberge** [comment]
你好，IterE_Loss目前已经在NeuralKG中弃用，因此如果遇到ModuleNotFoundError问题，可以选择删除`from .Iter_Loss import Iter_Loss`命令或更新NeuralKG。

当前NeuralKG默认使用GPU加速训练，采用CPU会极大延长训练时间。如果您当前需要使用CPU进行NeuralKG训练，只需将main.py的81行和91行命令改为`gpus=0`就可以简单实现，但请注意这种方法在一些模型中没有经过测试，因此我们还是推荐采用GPU加速模型训练的方法。
